### ISSUE TITLE
improve offline mapping experience

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/quilt-mappings#319]
Ideally, you should be able to run all mapping tasks while offline after downloading all required files once. This includes minecraft's files and the spelling dictionary.

tentative plan:
Save two values in a json file in the cache: minecraft version and most recent update. Consider cache update task up to date if the minecraft version matches the current constant and it's been less than a day since the last update. If it's been more than a day but the user is offline, warn and allow running anyway. Do not allow run if minecraft version does not match constant.

On run:
1. validate json file
if success, continue, otherwise redownload all files
2. check all necessary files are present
if success, continue, otherwise redownload all files

**Comment by IotaBread** [comment]
Most of this can already be done with what we have. The version manifest file contains the latest minecraft versions, and I think gradle can keep track of the time since the file was updated. Usually this file isn't updated more than once a week, so a single day of cache validity would be far too short.
On the other hand, I think we shouldn't block the user from mapping a version other than the latest one, since sometimes its useful to backport mappings from newer Minecraft versions, or even just compare mappings or code between them.

**Comment by eristhea** [comment]
thanks for the information!
I think I'm going to look at tackling this myself
