### ISSUE TITLE
`x/yRot` vs `pitch/yaw`

### ISSUE THREAD

**Issue by eristhea** [QuiltMC/quilt-mappings#605]
for describing rotation, mojang likes `x/yRot` while we mostly use `pitch` and `yaw`. i believe that we should move to match mojang here

**Comment by OroArmor** [comment]
hm i prefer pitch and yaw

**Comment by sylv256** [comment]
I'm going to drop my two cents here and agree with Oro. It makes more technical and intuitive sense to use `yaw` and `pitch` to describe axes of rotation, because one could reasonably confuse `xRot` for `yaw` (which is around the y-axis but moves on the same plane as the x-axis and z-axis), `zRot` for `pitch` (which is actually around the x-axis but moves on the same plane as the z-axis and y-axis), and `yRot` for `roll` (which is actually around the z-axis but moves on the same plane as the y-axis and x-axis). [Here's an illustration of what I'm trying to demonstrate](https://simple.wikipedia.org/wiki/Pitch,_yaw,_and_roll#/media/File:6DOF_en.jpg):
![The six degrees of freedom: forward/back, up/down, left/right, pitch, yaw, roll](https://upload.wikimedia.org/wikipedia/commons/f/fa/6DOF_en.jpg)

**Comment by sylv256** [comment]
I'd also like to add that with such unique names, it's hard to confuse them when debugging issues. `x/y/zRot` all being one letter away from each other can add confusion, especially when you aren't paying attention.

**Comment by eristhea** [comment]
these are good points -- i agree with sticking to pitch/yaw
i'll make a PR to convert existing `x/yRot` (all unchanged records) to pitch/yaw
